### ISSUE TITLE
Metrical won't install on ruby 1.9, because of rcov dependency.

### ISSUE THREAD

**Issue by johnmarkos** [iain/metrical#12]
The current version of rcov, 1.0.0, will not install on Ruby 1.9. I had to explicitly install the previous version, 0.9.11, then I could install metrical without error.

<pre>
$ gem install metrical
Building native extensions.  This could take a while...
ERROR:  Error installing metrical:
    ERROR: Failed to build gem native extension.

        $USER/.rvm/rubies/ruby-1.9.2-p290/bin/ruby extconf.rb
**** Ruby 1.9 is not supported. Please switch to simplecov ****

Gem files will remain installed in $USER/.rvm/gems/ruby-1.9.2-p290@<gemset>/gems/rcov-1.0.0 for inspection.
Results logged to $USER/.rvm/gems/ruby-1.9.2-p290@<gemset>/gems/rcov-1.0.0/ext/rcovrt/gem_make.out
</pre>

Workaround:

<pre>
$ gem install rcov --version 0.9.11
Building native extensions.  This could take a while...
WARNING: rcov-0.9.11 has an invalid nil value for @cert_chain
Successfully installed rcov-0.9.11
1 gem installed
Installing ri documentation for rcov-0.9.11...
Installing RDoc documentation for rcov-0.9.11...

$ gem install metrical
WARNING: Saikuro-1.1.0 has an invalid nil value for @cert_chain
Building native extensions.  This could take a while...
Successfully installed chronic-0.3.0
Successfully installed Saikuro-1.1.0
Successfully installed syntax-1.0.0
Successfully installed hirb-0.5.0
Successfully installed git-1.2.5
Successfully installed jeweler-1.6.4
Successfully installed json-1.6.1
Successfully installed json_pure-1.6.5
8 gems installed
Installing ri documentation for chronic-0.3.0...
Installing ri documentation for Saikuro-1.1.0...
Installing ri documentation for syntax-1.0.0...
Installing ri documentation for hirb-0.5.0...
Installing ri documentation for git-1.2.5...
Installing ri documentation for jeweler-1.6.4...
Installing ri documentation for json-1.6.1...
Installing ri documentation for json_pure-1.6.5...
Installing RDoc documentation for chronic-0.3.0...
Installing RDoc documentation for Saikuro-1.1.0...
Installing RDoc documentation for syntax-1.0.0...
Installing RDoc documentation for hirb-0.5.0...
Installing RDoc documentation for git-1.2.5...
Installing RDoc documentation for jeweler-1.6.4...
Installing RDoc documentation for json-1.6.1...
Installing RDoc documentation for json_pure-1.6.5...
</pre>

**Comment by emilianodellacasa** [comment]
That worked for me.

In Rails 3.x, you can also add

gem 'rcov', '0.9.11'
gem 'metrical'

in your Gemfile to make it work

**Comment by chalofa** [comment]
+1
same error + workaround that @johnmarkos 

having metrical and rcov in the Gemfile is not an option for me, because it adds a lot of gem dependencies

**Comment by RichardJordan** [comment]
Had same problem.  This worked fine for me without need to put stuff in the Gemfile.  Now metrical isntalls okay.  Cheers.

**Comment by pshoukry** [comment]
+1 works for me.

Thanks!

**Comment by iain** [comment]
rcov isn't a dependency of metrical, but of metric_fu. I cannot solve this for you

**Comment by emilianodellacasa** [comment]
What if someone fork metric_fu just to remove that dependency and make metrical depending from the fork?

**Comment by iain** [comment]
Now that I think of it some more, I could just depend on rcov 0.9 in metrical. This version doesn't block on 1.9.3, although it doesn't work.

**Comment by emilianodellacasa** [comment]
Worked for me, thanks!

**Comment by iain** [comment]
Metrical 0.1.0 is out.
