### ISSUE TITLE
ERROR:  While executing gem ... (Gem::DependencyError)

### ISSUE THREAD

**Issue by chalofa** [iain/metrical#13]
When installing the latest metrical version, I'm getting this error:

``` bash
$ gem install metrical
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: metric_fu requires chronic (~> 0.3.0);
    churn requires chronic (>= 0.2.3), map (= 4.3.0), chronic (>= 0.2.3);
    main requires chronic (>= 0.6.2), map (>= 5.1.0)
```

``` bash
$ ruby -v
ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-darwin11.2.0]

$ gem list
*** LOCAL GEMS ***

bundler (1.0.22)

$
```

**Comment by skull-squadron** [comment]
Yep, exact same error here.

**Comment by RichardJordan** [comment]
So I have got round this by cloning metrical and metric fu locally, and installing some of the dependencies in a specific order with specific versions (garnered through trial and error to be honest).  Works mostly for me.  I'll try to document and add a note here.

**Comment by RichardJordan** [comment]
if you're just wanting to get it working I added gems in this order:  

gem install chronic --version 0.3.0
gem install map --version 4.3.0
gem install main --version 4.7.1
gem install ../gems/metric_fu/metric_fu-2.1.1.gem from  # my local fork with some gemspec tweaks
then gem install metrical

works for me but i recognize not ideal...

**Comment by skull-squadron** [comment]
I've been using Gemfury a bit more on external gemsets to ragequit dependency hell.

**Comment by tommeier** [comment]
Getting this too - but due to dependency on 'Whenever' being Chronic > 0.6

**Comment by tommeier** [comment]
```
Bundler could not find compatible versions for gem "chronic":
  In Gemfile:
    metrical (~> 0.1.0) ruby depends on
      chronic (~> 0.3.0) ruby

    whenever (= 0.7.3) ruby depends on
      chronic (0.6.3)

```

**Comment by tommeier** [comment]
-> Solved by using (prior to metrical gem) : 

```
gem 'metric_fu' , :git => 'git://github.com/jnimety/metric_fu.git', :ref => '27a552c781feb90ab6d678622a5f45f26afad8b5', :require => false #Required - Otherwise dependency set on old chronic
```

**Comment by kurko** [comment]
Sucks, the churn gem won't install. There's a month old patch to fix it, but it's not merged. Let's wait or use and older metric_fu.

**Comment by swistak** [comment]
well dependency hell :/

**Comment by skull-squadron** [comment]
Gemfury can easily host a customized churn gem, no problem.  That's what it's mostly use for.

**Comment by skull-squadron** [comment]
Please point me to the ref of the working churn gem and the patch, I'll fix it.

**Comment by kurko** [comment]
https://github.com/danmayer/churn/pull/11

**Comment by RichardJordan** [comment]
@steakknife that'd be awesome :-)

**Comment by skull-squadron** [comment]
I've merged in rferrera's changes and a churn gem as 0.0.19.

``` shell

gem sources -a https://gems.gemfury.com/8n1rdTK8pezvcsyVmmgJ/
gem install churn -v0.0.19
```

… or with Bundler

``` shell
source 'http://rubygems.org' # or https://
source 'https://gems.gemfury.com/8n1rdTK8pezvcsyVmmgJ/'
.
.
.
gem 'churn', '>= 0.0.19'
```

I didn't much thoughtspace into it, but still getting: 

``` shell
gem install metrical
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: metric_fu requires chronic (~> 0.3.0)
```

I think we need a "pretend the reader never installed metric(al|_fu) before" simple howto that installs everything with bundler (probably just metric_fu) or normal (probably metrical).

Update: If you don't want my gems on an on-going basis, 

```
gem install churn -v0.0.19 --source https://gems.gemfury.com/8n1rdTK8pezvcsyVmmgJ/
```

**Comment by skull-squadron** [comment]
I've also just hosted unofficial metric_fu 2.1.1.1 with 1.9 (simplecov) support which also includes @tommeier 's suggestion.  If different preferred, let me know.

**Comment by swistak** [comment]
Well testing if gem is actually instalable should be pretty basic. Just after releasing create new rvm gemset and try to install.

This is the reason i hate when there's bunch of small projects all < 1.0 in dependencies.

**Comment by iain** [comment]
Hi,

Sorry for the late response. The only way to ensure that all dependencies are installed correctly is to use Bundler. Add metrical to your Gemfile. This works on Travis, so I'm betting it'll work for you as well.

I've given up on this gem, it's too much of a burden. Hope you'll understand.

**Comment by kurko** [comment]
Given the interest by some many people, you could hand an admin access to someone maintain it or redirect this commit to whomever decides to fork this. What do you think?

**Comment by iain** [comment]
I agree, I've already put a notification in the README to ask for a new maintainer. Just fork the repo and give me a notice and I will give you rubygems.org permissions and so on will be given.
