### ISSUE TITLE
Dependency Issue when installing

### ISSUE THREAD

**Issue by jezcaudle** [iain/metrical#14]
Churn is a culprit here. That won't install stand alone.

ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: churn requires chronic (>= 0.2.3), map (= 4.3.0), chronic (>= 0.2.3); main requires chronic (>= 0.6.2), map (>= 5.1.0); metric_fu requires chronic (~> 0.3.0)

ruby -v :  ruby 1.8.7 (2010-01-10 patchlevel 249) [universal-darwin11.0]

Gem List:

abstract (1.0.0)
actionmailer (3.2.1, 3.2.0, 3.1.3, 3.0.10, 3.0.9, 3.0.5)
actionpack (3.2.1, 3.2.0, 3.1.3, 3.0.10, 3.0.9, 3.0.5)
activemodel (3.2.1, 3.2.0, 3.1.3, 3.0.10, 3.0.9, 3.0.5)
activerecord (3.2.1, 3.2.0, 3.1.3, 3.0.10, 3.0.9, 3.0.5)
activeresource (3.2.1, 3.2.0, 3.1.3, 3.0.10, 3.0.9, 3.0.5)
activesupport (3.2.1, 3.2.0, 3.1.3, 3.0.10, 3.0.9, 3.0.5)
addressable (2.2.7)
arel (3.0.2, 2.2.3, 2.2.2, 2.2.1, 2.0.10, 2.0.9)
bcrypt-ruby (3.0.1, 2.1.4, 2.1.3)
builder (3.0.0, 2.1.2)
bundler (1.0.21)
cancan (1.6.7, 1.6.4, 1.5.0)
capistrano (2.9.0)
capybara (1.1.2)
capybara-webkit (0.11.0)
childprocess (0.3.1)
coffee-rails (3.2.2, 3.1.1)
coffee-script (2.2.0)
coffee-script-source (1.2.0)
database_cleaner (0.7.2)
devise (2.0.4, 2.0.0, 1.3.4, 1.2.1, 1.1.5)
devise_invitable (1.0.0, 0.5.0, 0.3.5)
erubis (2.7.0, 2.6.6)
exception_notifier (1.0.0)
execjs (1.3.0)
ffi (1.0.11)
hashie (1.2.0)
highline (1.6.11, 1.6.9, 1.6.1)
hike (1.2.1)
hpricot (0.8.6)
i18n (0.6.0, 0.5.0)
journey (1.0.3, 1.0.2)
jquery-rails (2.0.0, 1.0.19)
json (1.6.5, 1.6.4)
libwebsocket (0.1.3)
mail (2.4.1, 2.3.0, 2.2.19, 2.2.15)
meta_search (1.0.6)
mime-types (1.18, 1.17.2, 1.16)
mini_fb (1.1.7)
multi_json (1.1.0, 1.0.4)
net-scp (1.0.4)
net-sftp (2.0.5)
net-ssh (2.3.0, 2.2.1)
net-ssh-gateway (1.1.0)
nokogiri (1.5.2)
oauth (0.4.5)
orm_adapter (0.0.6, 0.0.4)
paperclip (2.3.6)
pjax_rails (0.1.10)
polyglot (0.3.3, 0.3.1)
rack (1.4.1, 1.3.6, 1.2.5, 1.2.4, 1.2.2)
rack-cache (1.1)
rack-mount (0.8.3, 0.6.14)
rack-pjax (0.5.7)
rack-ssl (1.3.2)
rack-test (0.6.1, 0.5.7)
rails (3.2.1, 3.2.0, 3.1.3, 3.0.10, 3.0.9, 3.0.5)
railties (3.2.1, 3.2.0, 3.1.3, 3.0.10, 3.0.9, 3.0.5)
rake (0.9.2.2, 0.8.7)
rdoc (3.12)
rest-client (1.6.7)
rmagick (2.13.1)
rubygems-update (1.8.15)
rubyzip (0.9.7)
sass (3.1.15)
sass-rails (3.2.4, 3.1.5)
selenium-webdriver (2.20.0)
simplecov (0.6.1, 0.5.4, 0.4.1)
simplecov-html (0.5.3, 0.4.3)
sitemap_generator (3.0.0, 1.3.8)
sprockets (2.1.2, 2.0.3)
sqlite3 (1.3.5, 1.3.4, 1.3.3)
sqlite3-ruby (1.3.3, 1.3.2)
thor (0.14.6)
tilt (1.3.3)
treetop (1.4.10, 1.4.9)
twitter_oauth (0.4.3)
tzinfo (0.3.32, 0.3.31, 0.3.25)
uglifier (1.2.3)
warden (1.1.1, 1.0.6, 1.0.3)
xpath (0.1.4)

**Comment by iain** [comment]
Hi,

Sorry for the late response. The only way to ensure that all dependencies are installed correctly is to use Bundler. Add metrical to your Gemfile.

I've given up on this gem, it's too much of a burden. Hope you'll understand.

**Comment by jezcaudle** [comment]
No need to apologise - you've done fantastic work and then found other stuff to do. A person will only do things they enjoy and once that it is gone it is time to pack up and move.

Good luck with what ever you are doing and I hope it is fun.

## Survivor by Roger McGough

Everyday,
I think about dying.
About disease, starvation,
violence, terrorism, war,
the end of the world.

It helps
keep my mind off things.

On Apr 26, 2012, at 07:44 PM, Iain Hecker reply@reply.github.com wrote:

Hi,

Sorry for the late response. The only way to ensure that all dependencies are installed correctly is to use Bundler. Add metrical to your Gemfile.

I've given up on this gem, it's too much of a burden. Hope you'll understand.

---
