### ISSUE TITLE
Roodi vs. Psych - solved.

### ISSUE THREAD

**Issue by camallen** [iain/metrical#15]
Re:

"If you're running Ruby 1.9 with Psych as your default YAML parser (possible in 1.9.2, and the default in 1.9.3), you might get an error message. I have no clue what to do about it. Some help on this would be greatly appreciated."

The problem is with the roodi.yml file (https://github.com/martinjandrews/roodi/blob/master/roodi.yml), see this ignored pull request: https://github.com/martinjandrews/roodi/pull/9. I've applied the change to my roodi.yml file and roodi now runs fine. 

It looks like the roodi gem has is not being maintained. One solution is to edit the yml file manually (what i did), the other is to publish a fixed version of the gem so the metric_fu gemspec can reference the fixed published gem.

It could be helpful to add the link to the fixed rood.yml file and pull request on the readme.  

I hope this saves someone else some time.
Cam

**Comment by iain** [comment]
Thanks for the solution.

Actually, I'm not maintaining metrical really anymore. There are too many problems with Ruby 1.9; most tools don't support new syntax; which I use. It looks like metric_fu also doesn't get much 1.9-love.

I will put a link to this issue on the README, though. Thanks for figuring it out :)
