### ISSUE TITLE
It isn't working with rvm 1.9.2

### ISSUE THREAD

**Issue by maxguzenski** [iain/metrical#4]
metrical 
ERROR! Aborting. You may want to run with --continue.
/Users/max/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/racc/parser.rb:349:in `on_error':  (Racc::ParseError)
parse error on value "." (tDOT)
    from /Users/max/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/racc/parser.rb:99:in`_racc_do_parse_c'
    from /Users/max/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/racc/parser.rb:99:in `do_parse'
    from /Users/max/.rvm/gems/ruby-1.9.2-p0/gems/ruby_parser-2.0.6/lib/ruby_parser_extras.rb:749:in`process'
    from /Users/max/.rvm/gems/ruby-1.9.2-p0/gems/flog-2.5.1/lib/flog.rb:241:in `block in flog'
    from /Users/max/.rvm/gems/ruby-1.9.2-p0/gems/flog-2.5.1/lib/flog.rb:235:in`each'
    from /Users/max/.rvm/gems/ruby-1.9.2-p0/gems/flog-2.5.1/lib/flog.rb:235:in `flog'
    from /Users/max/.rvm/gems/ruby-1.9.2-p0/gems/metric_fu-2.1.1/lib/generators/flog.rb:20:in`emit'
    from /Users/max/.rvm/gems/ruby-1.9.2-p0/gems/metric_fu-2.1.1/lib/base/generator.rb:130:in `block in generate_report'
    from /Users/max/.rvm/gems/ruby-1.9.2-p0/gems/metric_fu-2.1.1/lib/base/generator.rb:128:in`each'
    from /Users/max/.rvm/gems/ruby-1.9.2-p0/gems/metric_fu-2.1.1/lib/base/generator.rb:128:in `generate_report'
    from /Users/max/.rvm/gems/ruby-1.9.2-p0/gems/metric_fu-2.1.1/lib/base/report.rb:60:in`add'
    from /Users/max/.rvm/gems/ruby-1.9.2-p0/gems/metrical-0.0.5/bin/metrical:34:in `block in <top (required)>'
    from /Users/max/.rvm/gems/ruby-1.9.2-p0/gems/metrical-0.0.5/bin/metrical:34:in`each'
    from /Users/max/.rvm/gems/ruby-1.9.2-p0/gems/metrical-0.0.5/bin/metrical:34:in `<top (required)>'
    from /Users/max/.rvm/gems/ruby-1.9.2-p0/bin/metrical:19:in`load'
    from /Users/max/.rvm/gems/ruby-1.9.2-p0/bin/metrical:19:in `<main>'

**Comment by iain** [comment]
This is an issue with flay and flog. They cannot read 1.9.2 syntax. You'll have to disable them in your .metrics file
