### ISSUE TITLE
Chronic dependency

### ISSUE THREAD

**Issue by ghost** [iain/metrical#6]
Hi,

I am getting the following error when I try to run the metrical gem

braga@braga-laptop:~/prj/dummy_app$ metrical
/usr/local/lib/site_ruby/1.8/rubygems.rb:242:in `activate': can't activate chronic (~> 0.6.2, runtime) for ["main-4.7.3", "churn-0.0.13", "metric_fu-2.1.1", "metrical-0.0.6"], already activated chronic-0.3.0 for ["metric_fu-2.1.1", "metrical-0.0.6"] (Gem::LoadError)
    from /usr/local/lib/site_ruby/1.8/rubygems.rb:258:in`activate'
    from /usr/local/lib/site_ruby/1.8/rubygems.rb:257:in `each'
    from /usr/local/lib/site_ruby/1.8/rubygems.rb:257:in`activate'
    from /usr/local/lib/site_ruby/1.8/rubygems.rb:258:in `activate'
    from /usr/local/lib/site_ruby/1.8/rubygems.rb:257:in`each'
    from /usr/local/lib/site_ruby/1.8/rubygems.rb:257:in `activate'
    from /usr/local/lib/site_ruby/1.8/rubygems.rb:258:in`activate'
    from /usr/local/lib/site_ruby/1.8/rubygems.rb:257:in `each'
    from /usr/local/lib/site_ruby/1.8/rubygems.rb:257:in`activate'
    from /usr/local/lib/site_ruby/1.8/rubygems.rb:258:in `activate'
    from /usr/local/lib/site_ruby/1.8/rubygems.rb:257:in`each'
    from /usr/local/lib/site_ruby/1.8/rubygems.rb:257:in `activate'
    from /usr/local/lib/site_ruby/1.8/rubygems.rb:1146:in`gem'
    from /usr/bin/metrical:18

The Rails Version I am using is 2.3.14 and the Ruby version is 1.8.7

I read through a bunch of posts regarding metric_fu and metrical and many places I am seeing this dependency problem. Some of the blog posts say that they were resolved. But then they have become old enough and the dependent gems have updated themselves making the above error to appear again.

Can somone tell me how to resolve this error?

Thanks

**Comment by iain** [comment]
I've recently released a new version of metrical to deal with some related dependency issues. I've locked down the version of the gem called `main`, so it uses chronic 0.3.0.

You should try to get it to work in a clean gemset and install metrical 0.0.6.

**Comment by ghost** [comment]
Thanks iain.. Will try it right away.

**Comment by ghost** [comment]
Thanks. That helped me resolve the problem!!
