### ISSUE TITLE
Unable to resolve dependencies: metrical requires main (~> 4.6.0)

### ISSUE THREAD

**Issue by chalofa** [iain/metrical#8]
With ruby 1.9.3, when trying to install metrical:

**$ gem install metrical**
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: metrical requires main (~> 4.6.0); metric_fu requires chronic (~> 0.3.0); churn requires chronic (= 0.6.4), main (= 4.7.7), main (>= 0), chronic (>= 0.2.3)

**Comment by davidakachaos** [comment]
Same on ruby 1.8.7 (2011-06-30 patchlevel 352) [i686-darwin10.8.0]

**Comment by skull-squadron** [comment]
+1 for 1.8.x or 1.9.x

**Comment by snemetz** [comment]
Same on ruby 1.9.2p290 (2011-07-09 revision 32553) under rvm with a gemset.

installed main 4.7.7 and chronic 0.6.4 to get metrical to install

Then tried to run metrical and got:
rubygems.rb:274:in `activate': can't activate chronic (= 0.6.4, runtime) for ["churn-0.0.14", "metric_fu-2.1.1", "metrical-0.0.7"], already activated chronic-0.3.0 for ["metric_fu-2.1.1", "metrical-0.0.7"](Gem::LoadError)

Trying to run metric_fu directly got a similar error:
rake metric:all
rake aborted!
can't activate chronic (= 0.6.4, runtime) for ["churn-0.0.14", "metric_fu-2.1.1"], already activated chronic-0.3.0 for ["metric_fu-2.1.1"]

**Comment by danmayer** [comment]
This should be resolved now. This was my fault. I upgraded churn and locked some gems higher than they needed to be which caused both  metrical and metric_fu to fail to install. It should be resolved now that I released churn 0.0.15

Sorry about that.

**Comment by chalofa** [comment]
fixed for me! thanks :)

**Comment by skull-squadron** [comment]
Yay!  More holiday :cake: :beer: for you!
