### ISSUE TITLE
Dependency issue with ruby_parser

### ISSUE THREAD

**Issue by nielsm** [iain/metrical#9]
can't activate ruby_parser (~> 2.0.4, runtime) for ["churn-0.0.13", "metric_fu-2.1.1", "metrical-0.0.7"], already activated ruby_parser-2.3.1 for ["flay-1.4.2", "metric_fu-2.1.1", "metrical-0.0.7"](Gem::LoadError)

**Comment by pnegri** [comment]
Please!!!

May its the churn that is halting things up!

**Comment by rojeff** [comment]
what is the solution for this?

**Comment by iain** [comment]
Hi,

Sorry for the late response. The only way to ensure that all dependencies are installed correctly is to use Bundler. Add metrical to your Gemfile.

I've given up on this gem, it's too much of a burden. Hope you'll understand.
